account_id = "54ab4107e6546eaba296abd6810f2cc7"
compatibility_date = "2021-12-12"
name = "githubbox"
route = ""
type = "webpack"
workers_dev = true
zone_id = ""

[env.production]
# The ID of your domain you're deploying to
zone_id = "a4b67eb37bea4ba8fa9026911195fa39"
# The route pattern your Workers application will be served at
route = "githubbox.com/*"
